let userMap = [
    {
        id:"depart0",
        name:"内科",
        members:[
            {
                id:"1",
                name:"林超群",
                active:false
            },
            {
                id:"2",
                name:"张三",
                active:false
            },
            {
                id:"3",
                name:"李四",
                active:false
            }
        ]
    },
    {
        id:"depart1",
        name:"外科",
        members:[
            {
                id:"4",
                name:"王五",
                active:false
            },
            {
                id:"5",
                name:"李柳",
                active:false
            },
            {
                id:"6",
                name:"张燕",
                active:false
            }
        ]
    }
];
module.exports = userMap;
